/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ScheduleEstimateRouteImport } from './routes/schedule-estimate'
import { Route as SandingAndRefinishRouteImport } from './routes/sanding-and-refinish'
import { Route as RefinishingRouteImport } from './routes/refinishing'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as InstallationRouteImport } from './routes/installation'
import { Route as HardwoodFlooringRouteImport } from './routes/hardwood-flooring'
import { Route as FloorDiagnosticRouteImport } from './routes/floor-diagnostic'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleEstimateRoute = ScheduleEstimateRouteImport.update({
  id: '/schedule-estimate',
  path: '/schedule-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const SandingAndRefinishRoute = SandingAndRefinishRouteImport.update({
  id: '/sanding-and-refinish',
  path: '/sanding-and-refinish',
  getParentRoute: () => rootRouteImport,
} as any)
const RefinishingRoute = RefinishingRouteImport.update({
  id: '/refinishing',
  path: '/refinishing',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationRoute = InstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwoodFlooringRoute = HardwoodFlooringRouteImport.update({
  id: '/hardwood-flooring',
  path: '/hardwood-flooring',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorDiagnosticRoute = FloorDiagnosticRouteImport.update({
  id: '/floor-diagnostic',
  path: '/floor-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/floor-diagnostic': typeof FloorDiagnosticRoute
  '/hardwood-flooring': typeof HardwoodFlooringRoute
  '/installation': typeof InstallationRoute
  '/quiz': typeof QuizRoute
  '/refinishing': typeof RefinishingRoute
  '/sanding-and-refinish': typeof SandingAndRefinishRoute
  '/schedule-estimate': typeof ScheduleEstimateRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/floor-diagnostic': typeof FloorDiagnosticRoute
  '/hardwood-flooring': typeof HardwoodFlooringRoute
  '/installation': typeof InstallationRoute
  '/quiz': typeof QuizRoute
  '/refinishing': typeof RefinishingRoute
  '/sanding-and-refinish': typeof SandingAndRefinishRoute
  '/schedule-estimate': typeof ScheduleEstimateRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/floor-diagnostic': typeof FloorDiagnosticRoute
  '/hardwood-flooring': typeof HardwoodFlooringRoute
  '/installation': typeof InstallationRoute
  '/quiz': typeof QuizRoute
  '/refinishing': typeof RefinishingRoute
  '/sanding-and-refinish': typeof SandingAndRefinishRoute
  '/schedule-estimate': typeof ScheduleEstimateRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/floor-diagnostic'
    | '/hardwood-flooring'
    | '/installation'
    | '/quiz'
    | '/refinishing'
    | '/sanding-and-refinish'
    | '/schedule-estimate'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/floor-diagnostic'
    | '/hardwood-flooring'
    | '/installation'
    | '/quiz'
    | '/refinishing'
    | '/sanding-and-refinish'
    | '/schedule-estimate'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/floor-diagnostic'
    | '/hardwood-flooring'
    | '/installation'
    | '/quiz'
    | '/refinishing'
    | '/sanding-and-refinish'
    | '/schedule-estimate'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FloorDiagnosticRoute: typeof FloorDiagnosticRoute
  HardwoodFlooringRoute: typeof HardwoodFlooringRoute
  InstallationRoute: typeof InstallationRoute
  QuizRoute: typeof QuizRoute
  RefinishingRoute: typeof RefinishingRoute
  SandingAndRefinishRoute: typeof SandingAndRefinishRoute
  ScheduleEstimateRoute: typeof ScheduleEstimateRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule-estimate': {
      id: '/schedule-estimate'
      path: '/schedule-estimate'
      fullPath: '/schedule-estimate'
      preLoaderRoute: typeof ScheduleEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sanding-and-refinish': {
      id: '/sanding-and-refinish'
      path: '/sanding-and-refinish'
      fullPath: '/sanding-and-refinish'
      preLoaderRoute: typeof SandingAndRefinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinishing': {
      id: '/refinishing'
      path: '/refinishing'
      fullPath: '/refinishing'
      preLoaderRoute: typeof RefinishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installation': {
      id: '/installation'
      path: '/installation'
      fullPath: '/installation'
      preLoaderRoute: typeof InstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardwood-flooring': {
      id: '/hardwood-flooring'
      path: '/hardwood-flooring'
      fullPath: '/hardwood-flooring'
      preLoaderRoute: typeof HardwoodFlooringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-diagnostic': {
      id: '/floor-diagnostic'
      path: '/floor-diagnostic'
      fullPath: '/floor-diagnostic'
      preLoaderRoute: typeof FloorDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FloorDiagnosticRoute: FloorDiagnosticRoute,
  HardwoodFlooringRoute: HardwoodFlooringRoute,
  InstallationRoute: InstallationRoute,
  QuizRoute: QuizRoute,
  RefinishingRoute: RefinishingRoute,
  SandingAndRefinishRoute: SandingAndRefinishRoute,
  ScheduleEstimateRoute: ScheduleEstimateRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
